### ISSUE TITLE
The constructor must fail if conditions for isotopic cluster not met.

### ISSUE THREAD

**Issue by wolski** [protViz/deisotoper#49]
Check peak distances given charge and throw an exception if the distances do not agree with charge specified.

https://github.com/protViz/deisotoper/blob/44ae82964c84eeef0ce3f5aecabca8e9e43d8bed/java/deisotoper/src/main/java/ch/fgcz/proteomics/fbdm/IsotopicCluster.java#L55

**Comment by LukeCaruzo** [comment]
Done, see
https://github.com/protViz/deisotoper/blob/51d12fce8463f716a9c6c7707964777218694dc5/java/deisotoper/src/main/java/ch/fgcz/proteomics/fbdm/IsotopicCluster.java#L47
