### ISSUE TITLE
Make Constructor throw exeception if conditions for isotopic set are not met.

### ISSUE THREAD

**Issue by wolski** [protViz/deisotoper#50]
https://github.com/protViz/deisotoper/blob/b3095be77b8090f6a29f5d4e673474bf88768614/java/deisotoper/src/main/java/ch/fgcz/proteomics/fbdm/IsotopicSet.java#L27

**Comment by LukeCaruzo** [comment]
Done, see
https://github.com/protViz/deisotoper/blob/51d12fce8463f716a9c6c7707964777218694dc5/java/deisotoper/src/main/java/ch/fgcz/proteomics/fbdm/IsotopicSet.java#L56
