### ISSUE TITLE
Line length

### ISSUE THREAD

**Issue by wolski** [protViz/deisotoper#52]
https://github.com/protViz/deisotoper/blob/b3095be77b8090f6a29f5d4e673474bf88768614/java/deisotoper/src/main/java/ch/fgcz/proteomics/fbdm/IsotopicSet.java#L64

Please compliny with java codeconventions
http://www.oracle.com/technetwork/java/codeconventions-136091.html

**Comment by LukeCaruzo** [comment]
use standard

**Comment by LukeCaruzo** [comment]
Done, now it is the  'Java Conventions (eclipse built-in)', which has a limit of 80 characters per line.
