### ISSUE TITLE
merge into constructor and than call constructor from constructor

### ISSUE THREAD

**Issue by wolski** [protViz/deisotoper#54]
https://github.com/protViz/deisotoper/blob/75511f824b3175df88028f66084d4b0f7359382c/java/deisotoper/src/main/java/ch/fgcz/proteomics/fbdm/IsotopicMassSpectrum.java#L30

https://stackoverflow.com/questions/285177/how-do-i-call-one-constructor-from-another-in-java

**Comment by wolski** [comment]
Please attach commit information

https://help.github.com/articles/closing-issues-using-keywords/

**Comment by LukeCaruzo** [comment]
Done, see
https://github.com/protViz/deisotoper/blob/51d12fce8463f716a9c6c7707964777218694dc5/java/deisotoper/src/main/java/ch/fgcz/proteomics/fbdm/IsotopicMassSpectrum.java#L21
