### ISSUE TITLE
Move dependency IsotopicClusterGraph to IsotopicSet

### ISSUE THREAD

**Issue by wolski** [protViz/deisotoper#57]
https://github.com/protViz/deisotoper/blob/b3095be77b8090f6a29f5d4e673474bf88768614/java/deisotoper/src/main/java/ch/fgcz/proteomics/fbdm/Deisotoper.java#L55

The constructing the clusters, the graph, weighing the edges and computing the path should happen here.

**Comment by LukeCaruzo** [comment]
move aggregation function to isotopic cluster
