### ISSUE TITLE
Constructor and Method seems not to be used. if so remove.

### ISSUE THREAD

**Issue by wolski** [protViz/deisotoper#60]
https://github.com/protViz/deisotoper/blob/44ae82964c84eeef0ce3f5aecabca8e9e43d8bed/java/deisotoper/src/main/java/ch/fgcz/proteomics/fbdm/IsotopicCluster.java#L49

https://github.com/protViz/deisotoper/blob/44ae82964c84eeef0ce3f5aecabca8e9e43d8bed/java/deisotoper/src/main/java/ch/fgcz/proteomics/fbdm/IsotopicCluster.java#L45

And even if,  charge must be specified.

**Comment by wolski** [comment]
Attach information which commit resolves this issue.
https://help.github.com/articles/closing-issues-using-keywords/

**Comment by LukeCaruzo** [comment]
Done, see
https://github.com/protViz/deisotoper/blob/51d12fce8463f716a9c6c7707964777218694dc5/java/deisotoper/src/main/java/ch/fgcz/proteomics/fbdm/IsotopicCluster.java#L11
