### ISSUE TITLE
Remove dependency from DefaultDirectedWeightedGraph, 

### ISSUE THREAD

**Issue by wolski** [protViz/deisotoper#61]
https://github.com/protViz/deisotoper/blob/faf10077155ca558f27dbe3cc18e72ee6206c112/java/deisotoper/src/main/java/ch/fgcz/proteomics/fbdm/Score.java#L14

https://github.com/protViz/deisotoper/blob/faf10077155ca558f27dbe3cc18e72ee6206c112/java/deisotoper/src/main/java/ch/fgcz/proteomics/fbdm/Score.java#L247 really needs it move to own class.

**Comment by LukeCaruzo** [comment]
Done, see
https://github.com/protViz/deisotoper/blob/51d12fce8463f716a9c6c7707964777218694dc5/java/deisotoper/src/main/java/ch/fgcz/proteomics/fbdm/Score5.java#L10
