### ISSUE TITLE
Give more descriptive names to functions and make them static and public

### ISSUE THREAD

**Issue by wolski** [protViz/deisotoper#62]
https://github.com/protViz/deisotoper/blob/faf10077155ca558f27dbe3cc18e72ee6206c112/java/deisotoper/src/main/java/ch/fgcz/proteomics/fbdm/Score.java#L64

https://github.com/protViz/deisotoper/blob/faf10077155ca558f27dbe3cc18e72ee6206c112/java/deisotoper/src/main/java/ch/fgcz/proteomics/fbdm/Score.java#L101

https://github.com/protViz/deisotoper/blob/faf10077155ca558f27dbe3cc18e72ee6206c112/java/deisotoper/src/main/java/ch/fgcz/proteomics/fbdm/Score.java#L142

https://github.com/protViz/deisotoper/blob/faf10077155ca558f27dbe3cc18e72ee6206c112/java/deisotoper/src/main/java/ch/fgcz/proteomics/fbdm/Score.java#L194

**Comment by wolski** [comment]
You Still did not rename the functions. What is the firstNonIntensityScore computing?

**Comment by LukeCaruzo** [comment]
Done, see 
https://github.com/protViz/deisotoper/blob/51d12fce8463f716a9c6c7707964777218694dc5/java/deisotoper/src/main/java/ch/fgcz/proteomics/fbdm/Score.java#L10
