### ISSUE TITLE
implicitely import classes

### ISSUE THREAD

**Issue by LukeCaruzo** [protViz/deisotoper#63]
https://github.com/protViz/deisotoper/blob/5d171e2172f324bea89420dddebc6750fb049f87/java/deisotoper/src/main/java/ch/fgcz/proteomics/R/FeaturesBasedDeisotopingMethodR.java#L16

**Comment by wolski** [comment]
Attach information about which commit resolves this issue. 

https://help.github.com/articles/closing-issues-using-keywords/

**Comment by LukeCaruzo** [comment]
Done, see
https://github.com/protViz/deisotoper/blob/51d12fce8463f716a9c6c7707964777218694dc5/java/deisotoper/src/main/java/ch/fgcz/proteomics/R/FeaturesBasedDeisotopingMethodR.java#L16
