### ISSUE TITLE
Rename to FeatureBasedDeisotoping

### ISSUE THREAD

**Issue by wolski** [protViz/deisotoper#64]
https://github.com/protViz/deisotoper/blob/5d171e2172f324bea89420dddebc6750fb049f87/java/deisotoper/src/main/java/ch/fgcz/proteomics/R/FeaturesBasedDeisotopingMethodR.java#L18

**Comment by LukeCaruzo** [comment]
Done, see
https://github.com/protViz/deisotoper/blob/51d12fce8463f716a9c6c7707964777218694dc5/java/deisotoper/src/main/java/ch/fgcz/proteomics/R/FeaturesBasedDeisotoping.java#L22
