### ISSUE TITLE
All RJava interface methods into adapter, and return primitive types only

### ISSUE THREAD

**Issue by wolski** [protViz/deisotoper#65]
https://github.com/protViz/deisotoper/blob/5d171e2172f324bea89420dddebc6750fb049f87/java/deisotoper/src/main/java/ch/fgcz/proteomics/R/FeaturesBasedDeisotopingMethodR.java#L18

Configure deisotoping and read results.
Use method forwarding to call methods on classes in the Java implementation.

```{java}
calss FeaturesBasedDeisotopingMethodR{
 private Deisotoper deisotoper;
 private MassSpectrum massSpectrum;
 private MassSpectrum resultSpectrum;

void setParamters(double F1, double F2, double X3 ... ){
   this.deisotoper.setParams(F1,F2,F3)
}

void setMz(double[] mz){
   this.massSpectrum.setMz(mz);
}

void setIntensity(double[] intensity){
  this.massSpectrum.setIntensity(intensity);
}

 
double[] getMz(){
  this.resultSpectrum.getMz();
 }

double[] getIntensity(){
  this.resultSpectrum.getMz();
}


int[] getCharge(){
...
}

String[] getDotGraph(){
 this.deisotoper.getDotGraph();
}

String[] getSummary(){
 this.deisotoper.getSummary();
}

// etc.

```

**Comment by LukeCaruzo** [comment]
Done, see
https://github.com/protViz/deisotoper/blob/51d12fce8463f716a9c6c7707964777218694dc5/java/deisotoper/src/main/java/ch/fgcz/proteomics/R/FeaturesBasedDeisotoping.java#L22
