### ISSUE TITLE
Running examples in 'deisotoper-Ex.R' failed; Error: connections left open:

### ISSUE THREAD

**Issue by cpanse** [protViz/deisotoper#86]
<img width="540" alt="Screenshot 2019-03-30 at 20 44 25" src="https://user-images.githubusercontent.com/4901987/55280928-a3021580-532c-11e9-803d-bcc5b05e5205.png">
<img width="892" alt="Screenshot 2019-03-30 at 20 45 01" src="https://user-images.githubusercontent.com/4901987/55280931-be6d2080-532c-11e9-8b8f-c20f6763ed91.png">

<https://cran.r-project.org/web/checks/check_results_deisotoper.html>.

**Comment by cpanse** [comment]
@wolski 

```
From: Kurt Hornik <Kurt.Hornik@R-project.org>
To: <cp@fgcz.ethz.ch>
Subject: CRAN package deisotoper
CC: <CRAN@R-project.org>
Content-Type: text/plain; charset="UTF-8"
Reply-To: <CRAN@R-project.org>
Message-ID: <E1hFCUA-00009a-V7@aragorn.wu.ac.at>
Date: Sat, 13 Apr 2019 08:49:58 +0200
Content-Transfer-Encoding: quoted-printable
X-Filter-Node: phil4.ethz.ch
X-User-Whitelisted-Sender: Kurt.Hornik@R-project.org
Return-Path: Kurt.Hornik@R-project.org
X-MS-Exchange-Organization-AuthSource: edge20.ethz.ch
X-MS-Exchange-Organization-AuthAs: Anonymous
X-MS-Exchange-Organization-AVStamp-Mailbox: SMEXZmb@;1493500;0;This mail has
 been scanned by Trend Micro ScanMail for Microsoft Exchange;
X-MS-Exchange-Organization-SCL: 0
MIME-Version: 1.0

Dear maintainer,

Please see the problems shown on
<https://cran.r-project.org/web/checks/check_results_deisotoper.html>.

Please correct before 2019-04-27 to safely retain your package on CRAN.

Note that this will be the *final* reminder.

Best,
-k
```

**Comment by wolski** [comment]
My suspicion was that it was:
options(java.parameters = "- Xmx1000000m") 
so I changed it to:
options(java.parameters = "-Xmx1000m")

**Comment by cpanse** [comment]
![Screenshot 2019-04-25 at 10 42 11](https://user-images.githubusercontent.com/4901987/56722208-dc208080-6746-11e9-9c8f-c0b3420aac1b.png)
